version: '3'
services: 
    mongo:
        image: "mongo"
        ports: 
            - "27017:27017"
    flask:
        build: ./server
        image: "python:3.8.5-slim-buster"
        ports: 
            - "5000:5000"
